name: Lint PR

on:
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    strategy:
      matrix:
        php-version: ['7.4', '8.0', '8.1', '8.2']

    name: PHP ${{ matrix.php-version }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2, php-cs-fixer, vimeo/psalm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install composer
        run: composer install

      - name: Check Php code style
        run: php-cs-fixer fix

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          file_pattern: '*.php'
          branch: ${{ github.event.pull_request.head.ref }}

      - name: Run Psalm Static Analysis
        run: psalm --output-format=github
